select a.* exclude (SOURCE, INSERT_DATE, UPDATE_DATE, DML),
b.* exclude (order_key, SOURCE, INSERT_DATE, UPDATEDATE, DML) RENAME SOURCE_REGION as SOURCE_REGION_order,
c.*,
--d.* exclude (product_key, INSERTDATE,UPDATEDATE, DML),
--e.* exclude (warehouse_key, SOURCE, INSERTDATE, UPDATEDATE, DML) RENAME SOURCE_REGION as SOURCE_REGION_wh,


cd.CALENDAR_TYPE	as	SHIPPINGDATE_CALENDAR_TYPE	,
cd.DATE as SHIPPING_DATE,
cd.DAY_NAME	as	SHIPPINGDATE_DAY_NAME	,
cd.DATE_SEQUENCE	as	SHIPPINGDATE_DATE_SEQUENCE	,
cd.DATE_OF_YEAR	as	SHIPPINGDATE_DATE_OF_YEAR	,
cd.DATE_OF_QUARTER	as	SHIPPINGDATE_DATE_OF_QUARTER	,
cd.DATE_OF_MONTH	as	SHIPPINGDATE_DATE_OF_MONTH	,
cd.DATE_OF_WEEK	as	SHIPPINGDATE_DATE_OF_WEEK	,
cd.YEAR_NAME	as	SHIPPINGDATE_YEAR_NAME	,
cd.YEAR_SERIAL	as	SHIPPINGDATE_YEAR_SERIAL	,
cd.YEAR_SEQUENCE	as	SHIPPINGDATE_YEAR_SEQUENCE	,
cd.QUARTER_NAME	as	SHIPPINGDATE_QUARTER_NAME	,
cd.QUARTER_SERIAL	as	SHIPPINGDATE_QUARTER_SERIAL	,
cd.QUARTER_SEQUENCE	as	SHIPPINGDATE_QUARTER_SEQUENCE	,
cd.QUARTER_OF_YEAR	as	SHIPPINGDATE_QUARTER_OF_YEAR	,
cd.MONTH_NAME	as	SHIPPINGDATE_MONTH_NAME	,
cd.MONTH_SERIAL	as	SHIPPINGDATE_MONTH_SERIAL	,
cd.MONTH_SEQUENCE	as	SHIPPINGDATE_MONTH_SEQUENCE	,
cd.MONTH_OF_YEAR	as	SHIPPINGDATE_MONTH_OF_YEAR	,
cd.MONTH_OF_QUARTER	as	SHIPPINGDATE_MONTH_OF_QUARTER	,
cd.WEEK_NAME	as	SHIPPINGDATE_WEEK_NAME	,
cd.WEEK_SERIAL	as	SHIPPINGDATE_WEEK_SERIAL	,
cd.WEEK_SEQUENCE	as	SHIPPINGDATE_WEEK_SEQUENCE	,
cd.WEEK_OF_YEAR	as	SHIPPINGDATE_WEEK_OF_YEAR	,
cd.WEEK_OF_QUARTER	as	SHIPPINGDATE_WEEK_OF_QUARTER	,
cd.WEEK_OF_MONTH	as	SHIPPINGDATE_WEEK_OF_MONTH,

e.Warehouse_ID,
e.Warehouse_Name,
e.WH_Street,
e.WH_postal,
e.WH_City,
e.WH_State,
e.WH_country,
e.IsActive,
e.ParentWarehouse_Key,


from {{ref('FACT_ORDERDETAIL')}} a
left join {{ref('DIM_ORDER')}} b on a.order_key = b.order_key
left join {{ref('DIM_CALENDAR')}} c on a.order_date_key = c.date_key_2 and c.calendar_type = 'Retail Calendar'
--left join {{ref('DIM_PRODUCT')}} d on a.product_key = d.product_key
left join {{ref('DIM_WAREHOUSE')}} E on a.WAREHOUSE_key = E.WAREHOUSE_key
left join {{ref('DIM_CALENDAR')}} cd on a.shipping_date_key = cd.date_key_2 and cd.calendar_type = 'Retail Calendar'