SELECT DISTINCT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS RESTOCKTYPE_KEY,
a.restock_type,
'IO' AS DML,
a.source as SOURCE,a.source_region as SOURCE_REGION, current_timestamp() AS INSERTDATE, NULL AS UPDATEDATE
FROM {{ref('SHOPIFY_ORDER_LINE_REFUND')}} a